export const UPDATE_LOCATIONS_FETCHING = 'UPDATE_LOCATIONS_FETCHING';
export const UPDATE_LOCATIONS_LIST = 'UPDATE_LOCATIONS_LIST';
export const UPDATE_LOCATIONS_ITEM = 'UPDATE_LOCATIONS_ITEM';
export const UPDATE_LOCATIONS_OFFSET = 'UPDATE_LOCATIONS_OFFSET';

